### PR TITLE
Checkstyle: Adds checks preventing system defaults

### PR DESCRIPTION
**Pull request by adamvoncorswant**
That are not suitable for server-side development

Note: These checks are not all the ones we use internally in other scripts, but only the ones that's generic enough to be applicable to any java server-side project.

@nzroller or @xiaodong-izettle : How do we go about this? First merge and release the checkstyle artifact, and then update the basepom?

Also: Can anyone come up with more checks like this? What have I missed?

### CODE REVIEW

**Comment by adamvoncorswant** [comment]
fyi @jakobhenriksson

**Comment by adamvoncorswant** [comment]
This is a beautiful butterfly. Someone wanna merge? 
@trdarr , @xiaodong-izettle : doubts?

**Comment by xiaodong-izettle** [comment]
👍

**Comment by adamvoncorswant** [comment]
Hehe, thanks @xiaodong-izettle :dart:

**Pull request merged**
