### PR TITLE
Add vulnerability profile and upgrade plugins

### PR DESCRIPTION
**Pull request by chas678**
1) Add new Profile that runs a check against the dependencies and the National Vulnerability Database.  This is configured to fail if vulnerabilities with a CVSS value greater than 4 are found.  The value of 4 was chosen by the security team.   Because the initial database download takes a couple of minutes, this plugin is behind a profile.  To check your project run:   mvn -P dep-vuln-check clean verify . The intention is that a an extra Team City job for a project would execute this profile regularly and report vulnerabilities found so the team can take action by upgrading 3rd party libraries found with security flaws.
2) Updated plugins and dependency versions.  New versions were tested against Sun build.  Notably Checkstyle plugin now copes better with Java 8 lamdas and streams, and code format in projects may have to change a little.  The failsafe and surefire plugins have a number of bugfixes, coping better with concurrent tests (such as mvn -T 1.5C clean install # 1.5 thread per cpu core ) and named parameterized junit tests.

### CODE REVIEW

**Comment by ssprang** [comment]
Looks good to me! :+1: 
@nzroller , any remarks?

**Comment by nzroller** [comment]
:+1: @chas678 I'll try it out on a few projects.

**Comment by chas678** [comment]
@nzroller :+1:  FYI I have tested this on Sun master.  The new checkstyle version is better with Java8'isms and needed some changes.  I have a branch with these all corrected awaiting release of the new parent pom so I can push a PR using them.

**Comment by nzroller** [comment]
Great! I'll merge.

**Pull request merged**
