### PR TITLE
Remove EqualsAvoidNull checkstyle rule

### PR DESCRIPTION
**Pull request by erikryverling**
Many of you are familiar with the fact that 

> You read much more code than you write

Hence we should favor readability over cleverness. 

That's why I argue that we should **not** enforce the `EqualsAvoidNull` rule, which in my opinion is a clever hack to avoid NPE's that lessens readability. 

If you are concerned with NPE's when checking strings you should instead do some the following:
* Make sure to that the `String` variable is initialized before checking
* Use [`Optional`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html)
* Use the null-safe [`Objects.equals()`](http://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#equals(java.lang.Object,%20java.lang.Object))

@iZettle/izettle-dev

### CODE REVIEW

**Comment by geoaxis** [comment]
@Eric 

I don’t think this rules stops us from doing the 3 stated things. It does not enforce any bad readability either.  Can you give an example 

I see the example on check style page 
http://checkstyle.sourceforge.net/config_coding.html#EqualsAvoidNull <http://checkstyle.sourceforge.net/config_coding.html#EqualsAvoidNull>

**Comment by FredrikMunter** [comment]
If you mean that the rule enforces `Constant.equals(variable)` ("yoda code") then :+1: If not, I don't understand the change.

**Comment by erikryverling** [comment]
The rule enforces that the following expression

```java
variable.equals("value");
```

should be changed into

```java
"value".equals(variable);
```

**Comment by mxns** [comment]
I am all for removing this rule. Too much check style micro management is not good for code quality and frustration levels. Things like this that are not absolutely clear cut can be better solved in code reviews and discussions.

**Comment by geoaxis** [comment]
I have no problem reading in Joda code (I think). For this change - instead of taking out this rule we should encourage use of optionals.

**Comment by aaanders** [comment]
We should be able to assert that a String variable is not null and do `name.equals("anders")`. There is no valid reason to forbid that?

If it actually is null and I expect it not to be null. How does this rule help me?

**Comment by minisu** [comment]
I'm in favor of this PR, since there are cases where `variable.equals("value")` is preferred.

From the top of my head, let's say I have a class `Person` with a String field called `name`. I have established the nullability for this field somehow (e.g. using `@NotNull`, or `checkNotNull` in the constructor). I.e. for this business domain a null name can never make sense.

```java
class Person {

        private final String name;

        Person(String name) {
            this.name = checkNotNull(name);
        }
}
```

Now I want to implement `Person.isSanta()`:

```java
        boolean isSanta() {
            return name.equals("Santa Claus");
        }
```

With this implementation we are asserting our assumption that `name` is not nullable. If some future refactoring accidentally removes `checkNotNull` (or breaks annotation checks for `@NotNull`), the NPE will happen in `isSanta()` instead of in the constructor. We would probably discover the bug we introduced in refactoring quite early.

If we'd been forced to go Yoda in this case (`"Santa Claus".equals(name)`), not only would it read a bit more awkwardly, but `isSanta()` would just return `false` and we would probably discover the bug much later (maybe in production).

I think that Checkstyle rules should be used for consistent code styling and to prevent code that never make sense. This rule prevents code that sometimes makes a whole lot of sense.

**Comment by erikryverling** [comment]
@minisu Good point!

**Comment by adamvoncorswant** [comment]
I think I agree with your reasoning.

**Comment by MrShish** [comment]
>I think that Checkstyle rules should be used for consistent code styling and to prevent code that never make sense. This rule prevents code that sometimes makes a whole lot of sense.
like it, check style should check code style, curly braces and such. 

Word! :+1:

**Comment by softarn** [comment]
Agree, let's remove it. Fail fast and use Optional instead of returning null values.

**Comment by psvanstrom** [comment]
I just want to make it clear that the coding style is called _Yoda_ not Joda, named after the Grand Jedi Master Yoda :smile: 

Use correct names, you must!

https://en.wikipedia.org/wiki/Yoda#Character_overview

**Comment by psvanstrom** [comment]
Also, I agree with the reasoning above :+1:

**Comment by softarn** [comment]
Seems like almost everyone agrees

**Comment by erikryverling** [comment]
Yup, plz merge this anyone!

**Comment by erikryverling** [comment]
Hip hip hooray! :fireworks:

**Pull request merged**
