### PR TITLE
java 9 is officially released, let's allow it

### PR DESCRIPTION
**Pull request by davidodelberg**
is this how you allow it? 

`brew install java` now gives java 9 so this makes sense to me...
But this might have implications that I don't understand

### CODE REVIEW

**Comment by davidodelberg** [comment]
Actually it probably doesn't work because of source and target.

**Comment by adamvoncorswant** [comment]
Cool. I agree that we should try to get java9 out in the field as quick as possible! @nzroller : is this the way to initiate that?

**Comment by nzroller** [comment]
@adamvoncorswant I think this is a first step. Ironically the enforcer plugin itself (latest version v1.4.1) appears to not support java 9:

* https://issues.apache.org/jira/browse/MENFORCER-275 and 
* https://issues.apache.org/jira/browse/MENFORCER-274

There is a version to be released `3.0.0-M1` that has a fix for this so when that is out we'll need to do plugin version updates: 
* https://github.com/apache/maven-enforcer/tree/enforcer-3.0.0-M1

**Comment by rickard-von-essen-iz** [comment]
I think you will be in for a ride if you try to use Java 9 with Maven at the current state. See [Maven - Java 9 Jigsaw](https://cwiki.apache.org/confluence/display/MAVEN/Java+9+-+Jigsaw).

**Comment by xiaodong-izettle** [comment]
I successfully made email-service compile with Java9 several weeks back (with some tweaks of the pom file of course), but the tests failed. Dropwizard is not ready yet. 
And Wildfly is not ready yet. So possibly I'll have another look later this week. 

Migration to java9 for Sun should be easier than last time we migrated Sun to java8, as we switched application server at the same time.

**Comment by adamvoncorswant** [comment]
Thanks guys. Yeah, I suppose we'll have to wait at least for maven with the current PR. Still: there's no time to loose! :dancer:

**Comment by davidodelberg** [comment]
Like I said, this might have implications I'm not aware of 😄 

Anyway, this was because @furesjoiz got java 9 by default from brew. We downgraded to java 8 on his machine. 

This still doesn't update source or target so my assumption was that it would not impact anything besides local builds. But maybe it's better to not have people like me doing this :) I'll close this and leave it to the pros

**Pull request closed without merging**
