### PR TITLE
Align maven-checkstyle-plugin configurations

### PR DESCRIPTION
**Pull request by oskarli**
Not sure who should review or approve this change, feel free to add yourself to reviewers.

This change will align the configuration so that `checkstyle:check` uses the same settings as the `validate`-goal does. Otherwise the plugin will default to `sun_checks.xml` instead of our `checkstyle/checkstyle.xml`, which is used when you compile your project since the `validate`-goal runs in the compile phase.

### CODE REVIEW

**Comment by xiaodong-izettle** [comment]
@nzroller, your comments here? 😄

**Comment by nzroller** [comment]
Also how does the plugin default to `sun_checks.xml`? I don't find any references to `sun_checks.xml` anywhere in this repository.

**Comment by xiaodong-izettle** [comment]
@nzroller, see here: https://maven.apache.org/plugins/maven-checkstyle-plugin/check-mojo.html

**Comment by oskarli** [comment]
Updated the osspom projected too.

**Comment by xiaodong-izettle** [comment]
Cool, thanks, @oskarli. 👍

**Pull request merged**
